inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: disable
  SuggestExtensions: false
  Include:
    - 'app/classes/**/*.rb'
    - 'app/services/baseload/*.rb'

#    - 'app/models/**/*.rb'
#    - 'app/services/**/*.rb'
    - 'spec/**/*.rb'
  Exclude:
#    - 'app/models/**/*'
    - 'config/**/*'
    - 'InputData/**/*'
    - 'script/**/*'
    - 'lib/**/*'
    - 'log/**/*'
    - 'test_output/**/*'
    - 'test_support/**/*'
require:
  - rubocop-performance
  - rubocop-rspec

Naming/MethodParameterName:
  AllowedNames: ['kw', '£', 'co2']
Naming/VariableName:
  AllowedPatterns: ['_£','£']
Naming/MethodName:
  AllowedPatterns: ['_£', 'co2', '£']
Naming/AsciiIdentifiers:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/Documentation:
  Enabled: false
