AllCops:
  NewCops: enable
  Exclude:
    - 'app/models/**/*'
    - 'config/**/*'
    - 'InputData/**/*'
    - 'script/**/*'
    - 'lib/**/*'
    - 'log/**/*'
    - 'rakelib/**/*'
    - 'test_output/**/*'
    - 'test_support/**/*'
    - 'spec/app/models/**/*'
    - 'spec/lib/**/*'
Naming/AsciiIdentifiers:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/Documentation:
  Enabled: false  
