inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: disable
  SuggestExtensions: false
  Include:
#    - 'app/classes/**/*.rb'
#    - 'app/models/**/*.rb'
#    - 'app/services/**/*.rb'
    - 'spec/**/*.rb'
  Exclude:
#    - 'app/models/**/*'
    - 'config/**/*'
    - 'InputData/**/*'
    - 'script/**/*'
    - 'lib/**/*'
    - 'log/**/*'
    - 'test_output/**/*'
    - 'test_support/**/*'
require:
  - rubocop-performance
  - rubocop-rspec

Naming/AsciiIdentifiers:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/Documentation:
  Enabled: false
