language: ruby
cache:
  bundler: true
dist: bionic
addons:
  sources:
  - google-chrome
  apt:
    packages:
    - google-chrome-stable
sudo: required
before_install:
  - gem install bundler -v '2.1.4'
script:
- bundle exec bundle-audit check --update
- bundle exec rspec
