# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  rspec_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7.8', '3.0.6']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run tests
      run: bundle exec rspec

  analytics_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7.8', '3.0.6']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Run standard test
      run: ANALYTICSTESTDIR=test_output bundle exec ruby script/standard/standard_test_github_actions.rb

    # - name: Run standard tests
    #   run: ANALYTICSTESTDIR=test_output bundle exec ruby script/standard/standard_test.rb

    # - name: Run adult dashboard tests
    #   run: ANALYTICSTESTDIR=test_output bundle exec ruby script/standard/test_adult_dashboard.rb

    # - name: Run alert tests
    #   run: ANALYTICSTESTDIR=test_output bundle exec ruby script/standard/test_alerts.rb

    # - name: Run alert heating off forcast scenarios tests
    #   run: ANALYTICSTESTDIR=test_output bundle exec ruby script/standard/test_alerts_heating_off_forecast_scenarios.rb

    # - name: Run all test
    #   run: ANALYTICSTESTDIR=test_output bundle exec ruby script/standard/test_all

    # - name: Run all short test
    #   run: ANALYTICSTESTDIR=test_output bundle exec ruby script/standard/test_all_short.rb

    # - name: Run benchmarks tests
    #   run: ANALYTICSTESTDIR=test_output bundle exec ruby script/standard/test_benchmarks.rb

    # - name: Run building simulator tests
    #   run: ANALYTICSTESTDIR=test_output bundle exec ruby script/standard/test_building_simulator.rb

    # - name: Run charts tests
    #   run: ANALYTICSTESTDIR=test_output bundle exec ruby script/standard/test_charts.rb

    - name: Upload test artifacts
      uses: actions/upload-artifact@v3
      with:
        name: analytics-test-artifacts
        path: |
          test_output
          !./test_output/MeterCollections
          retention-days: 7

